use customer_behaviour

SELECT * FROM customer_shopping_behavior;

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue from customer_shopping_behavior group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount from customer_shopping_behavior where discount_applied = 'yes'and purchase_amount >= (select AVG(purchase_amount) from customer_shopping_behavior)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased, 
    AVG(review_rating) AS [averageProduct Rating]
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
Round(AVG(purchase_amount),2) from customer_shopping_behavior 
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status ,COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer_shopping_behavior
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
ROUND(100 * SUM(case when discount_applied = 'yes' then 1 else 0 end)/COUNT(*),2) as discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases IS NULL THEN 'Unknown'
            WHEN previous_purchases <= 1 THEN 'New'           -- 0 or 1 previous purchases => New
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'                                     -- 11+ => Loyal
        END AS customer_segment
    FROM dbo.customer_shopping_behavior
)
SELECT 
    customer_segment,
    COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY total_customers DESC;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5 
group by subscription_status


--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group, 
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;
